# Generated by Django 4.0.1 on 2022-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_alter_odam_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.IntegerField(default='1000000')),
            ],
        ),
    ]
