# Generated by Django 3.2.9 on 2021-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_data_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_img', models.FileField(upload_to='categories/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
