# Generated by Django 4.0 on 2021-12-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_registertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertable',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registertable',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registertable',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registertable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registertable',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='registertable',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registertable',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='registertable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='registertable',
            name='phone',
            field=models.IntegerField(default='998995150525'),
        ),
    ]
