# Generated by Django 4.0 on 2021-12-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0005_registertable_about_registertable_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Katalog'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Aloqa'},
        ),
        migrations.AlterModelOptions(
            name='registertable',
            options={'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterField(
            model_name='registertable',
            name='phone',
            field=models.IntegerField(default='998991112233'),
        ),
        migrations.AlterField(
            model_name='registertable',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profiles/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Add_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('product_img', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
